# Change these first
owner: silentsoft # Your GitHub username
repo: status.silentsoft.org # Your GitHub repository name

# Add your sites here
sites:
  - name: Central Server
    url: https://silentsoft.org
  - name: Actlist
    url: https://actlist.io
  - name: Blog
    url: https://blog.silentsoft.org
  - name: Nexus
    url: https://nexus.silentsoft.org
  - name: Portfolio
    url: $PORTFOLIO
  - name: API Endpoint
    url: $API_ENDPOINT

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.silentsoft.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/silentsoft/status.silentsoft.org/master/assets/upptime-icon.svg
  name: Status
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Contact
      href: mailto:contact@silentsoft.org

commitMessages:
  commitAuthorName: "silentsoft"
  commitAuthorEmail: "silentsoft@users.noreply.github.com"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
